keychain:
  applogic:
    algorithm: RS256
    value: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6N3l1OVpSSnRjRTZOc3ZHWlU5SApSNW5nTCtpK1dFaEhYQy96cmt1Yld5RnRZVGszMmxTVE9VdHEybVpFVE11ek0zVmhGREJZKyszQis0T24vdU1RCmRqMlBQU1JSTThCSzNObUZ4a0NoY1VUTS9SUzU1WFBXU2R4QWtIZXpaaURwMW9KSlNiY2I1Q1N3Y3R0ZVhTOWQKOHFhQ1NqYWIvS1pYY2pRN2poSjBjTDVIYjNwU0V4SUNJb1d2QUg1Uk1rOTQ5WUdld2RRSmtXdk02U1RjUXFoSApnVTdzRGcyQmk1R2haa0w1N21VUGFmbEFjdEl2bHFHeG5VWk9wVExLMy9WaEtvelRtLzR6aElOTFdrY1ZPUzh2Cmk2WjBGOXlNanp2Nk8wZlFlTDdJUkJiNFlFSm1QWm84eVZ4QzdvZnNWcThRYWNaQnEzc2ZZNGwyNEVSdVp5R1QKendJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==

scopes:
  read_withdraws:
    mandatory_signers:
      - applogic
    permitted_signers:
      - applogic
  write_withdraws:
    mandatory_signers:
      - applogic
    permitted_signers:
      - applogic

jwt: {}
